# Generated by Django 3.1.3 on 2020-11-22 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201122_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='store_product',
            new_name='storeproduct',
        ),
    ]
